travis:
  secure:
    BINSTAR_TOKEN: aYuAp73J0mrNmyYRsm/xAy+XHYIxHpss54EoB7SXVbRh2odWImrJzynob9n8uWL/4FznFlP5BKB/1S7wMVO4W6gAAesWiq7L5BgTajt1slEsOOmbbrks5z2nPrDeibqBSyiB/XNohR5MMw0mF8uimbcm7/FX2r11xwnKPhduZDHr2BY+w3WQoXv3/+4d+PP7ok8wouJGxLjDrqre9qLEsBPJO6mG26SBIgkfBHgDjb4TQ8jFMpHdbBYpVctxyDmZsrEzVX9EH7v4Up4KcR+g04tN2mWS1Oz1S6Lo12BQzW9pFQXjxTsbD4zrGZqXx8F2S0qbLo42e5ABSsrGSzWIahn2w10+r0AJlgROVnI2CkP8a+im8+bBvlOjNoN/qax8ZPndUZEafWJdtVd/XJL1zwKAwrN98zJJpzvp3Pv/xasFWMzOVO22O7s2RcwCKJ94yyVd7LAAA2JZWsdfalcsDvkw7VpA+6Qck2R1x4oOIbqGpA12KF6Z6hw2fyqPkvlxURT91yoz5b92+kYirMBL1Lr5I9Q2Jej30QzkE2a/NIVxjLK+1oedfklW+aM3bFKz9NqkRzWbcY0cKT5XggU/1ab3hGsRM8PPTZivA2F4WPX8GHHjG7rU2ZvO13IXjOGdd76fwcUhRoueXXG8J1KtITtXNJeWGMNRn8pLbIH8AyA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
