travis:
  secure:
    BINSTAR_TOKEN: KAbaCxy/g9f7l4a2ams0ylmj3J4OeEmHNLgMipkiHipPABNsaZWVfjuwqX5To3ykmt8V1R5VSLiWKk7S59mXXXQkFkLXf/dE6jpgqG+AOr4swvlqfsHcghgle9wntM3nOgI/nebHAzZwBI23M64FJ6VMzgUaKKP8V+Lv5JNruqSsJvblXnZZjyickoaEWZxxVEdP5NAg02Y5Up06IWewRSUB6wwLI4RkIaLjBJgkkjXouPO2GUNuarMh41e2Aa9O+8Xv0aGEphYWD921CwjXlVH8XP+ISh3yfW3axxnZvYXCmSMdQBEoFxYCJ9kZsZXHc8klVqxDzlBToyB68wHhIk7BDfPy4n2uNzL3FXvhI2OS9z5shdSrgXy04t6gHOfztNVzp+rvpH1rsjX+i8hssR8RWpz3SwqEdyR6IqQUvWiCHgQP5dkLk+5PSLRKxrmv6+Aygi7al7+ve037LsBLFak1pOfdPuE9+d0Sm70WTIxThTOePCz0Tof81JHGklsrI5sDXwe3I+gNd4hvrulQ0xb1vEDRKsgGezk43TSmxqQg275fXsGJz5o5pLGBFpUOmQE3D2VpXOQ/lm2O1z1c1j6tK4RXqAF7cyTTqP60JoOfNUSEtpRuM/gIkf80XGo8q10vqXvLF5mN4f6Ke/g7Yrgg+5fDyniPZB68wZJR7n0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
